import { Outfit,Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Shared/Header/Navbar";
import TopHeader from "@/Components/Shared/Header/TopHeader";

// Google Fonts


const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-outfit",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${outfit.variable} ${poppins.variable} antialiased`}
      >
        <TopHeader></TopHeader>
        <Header />
        {children}
      </body>
    </html>
  );
}
